name: CD
on:
  push:
    branches: [ wip ]
    tags:
      - '!*'
  pull_request:
    branches: [ wip ]
jobs:
  Tag:
    outputs:
      generated_tag: ${{ steps.BumpTag.outputs.new_tag }}
    runs-on: ubuntu-20.04
    steps:
      - name: CheckOut
        uses: actions/checkout@main
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        id: BumpTag
        uses: anothrNick/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
  Build:
    needs: [Tag]
    container: archlinux
    runs-on: ubuntu-20.04
    steps:
    - name: Env
      run: |
        pacman-key --init && pacman-key --populate
        curl -Ls https://gist.github.com/koumaza/afbcb7d36c629636d5c6c14a45317d4c/raw/7f17d171e19fb54190d51bb72d20c9fc0e048c32/pacman.conf > /etc/pacman.conf
        pacman -Syyuuv --noconfirm --needed --color always \
          archlinux-keyring base base-devel sudo repo git git-lfs python-pip go zstd
        useradd -md /home/repo -p repo repo && echo 'repo ALL=NOPASSWD:ALL' >> /etc/sudoers
        su repo -c "
          git clone https://aur.archlinux.org/yay-git.git --depth=1 --single-branch ~/.yay-git-aur && export ____pwdchan=$PWD && cd ~/.yay-git-aur && yes|makepkg -si && cd $____pwdchan
          yes ''|yay -Syyuu --needed --devel --timeupdate \
            linux-tools-meta \
            android-sdk android-sdk-platform-tools android-udev aosp-devel bc bison ccache curl esd-oss flex gcc-libs-multilib gcc-multilib git gnupg gperf inetutils jdk-openjdk lld lib32-gcc-libs lib32-glibc lib32-libusb lib32-libusb-compat lib32-ncurses lib32-ncurses5-compat-libs lib32-readline lib32-zlib libpng libtool-multilib libusb libusb-compat libxslt mesa multilib-devel ncurses ncurses5-compat-libs perl perl-switch pngcrush python2 readline repo rsync schedtool sdl squashfs-tools tcp_wrappers termcap unzip wxgtk zip zlib lib32-libpng xcur2png gnuplot ttf-droid ttf-dejavu fontconfig && \
        echo Tools are Installed
        "
        
        
    - name: Build
      shell: bash
      run: |
        mkdir -p ~/recovery_${GITHUB_REPOSITORY}
        cd ~/recovery_${GITHUB_REPOSITORY}
        repo init -u git://github.com/PitchBlackRecoveryProject/manifest_pb.git -b android-10.0
        repo sync -c -j$(($(nproc --all) * 24)) --force-sync --no-clone-bundle --no-tags
        mkdir -p device/blackshark && git clone https://github.com/${GITHUB_REPOSITORY}.git --depth=1 --single-branch device/blackshark/klein && cd device/blackshark/klein && git lfs pull && cd ../../../
        . build/envsetup.sh
        lunch koumaza_klein-eng
        mka recoveryimage
